### ISSUE TITLE
2025 Roadmap

### ISSUE THREAD

**Issue by AuroraZiling** [AuroraZiling/pipManager#3]
## Test

- [ ] #9

### Features

- [x] Detect Non-release Version *while updating, installing or downloading*
- [x] Install via distribution file
- [x] New pop-up overlay application
- [x] Pip Cache Clear
- [ ] Fix Search **Release 0.1.6**
- [ ] Complete environment support **Release 0.2.0**
  - [ ] Identifier
  - [ ] Virtual Environment #24 
- [ ] Software Update **Release 0.3.0**
- [ ] Scenario Recommendation **To be determined**

### Website

- [ ] Introduction
- [ ] Features
- [ ] Development
- [ ] Feedback
- [ ] About
- [ ] Beginner Tips #2
